#!/bin/csh
# Insert job name here 
#PBS -N 
# Project name (always xray)
#PBS -P phdam
# Number of CPUS 
#PBS -l select=1:ncpus=16:mem=32GB
# Amount of time for job (hrs:min:sec)
#PBS -l walltime=16:00:00
# Apparently emails when job ends or aborts
#PBS -m bae
# Queue to submit to 
#PBS -q scavenger 
# Something about changing to work dir

module load python/3.7.2
virtualenv --system-site-packages tf
source tf/bin/activate

module load cuda/10.0.130
module load openmpi-gcc/4.0.3
pip install /usr/local/tensorflow/v100/cuda10/tensorflow-1.15.0-cp37-cp37m-linux_x86_64.whl
pip install keras
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
pip install contractions

cd $PBS_O_WORKDIR


